### ISSUE TITLE
Doesn't seem to work well on OS X

### ISSUE THREAD

**Issue by waldyrious** [nomeata/darcs-mirror-arbtt#3]
I've been having some trouble using arbtt on OS X. I've installed it and set it for running on startup, but I suspect the sleep-wakeup cycles mess up with the program, resulting in data not being properly recorded. Here's the output of arbtt-dump:

```
$ arbtt-dump -l 10
2016-07-17 15:29:58 (964ms inactive):
2016-07-17 15:30:58 (3713ms inactive):
2016-07-17 15:31:59 (51ms inactive):
2016-07-17 15:32:59 (2ms inactive):
2016-07-17 15:33:59 (76ms inactive):
2016-07-17 16:02:32 (28294ms inactive):
2016-07-17 16:56:48 (88623ms inactive):
2016-07-17 17:51:03 (148952ms inactive):
2016-07-17 18:33:49 (12ms inactive):
2016-07-17 18:34:49 (68ms inactive):
```

@vrasneur any hints?

**Comment by vrasneur** [comment]
I don't know how the sleep-wakeup cycles could interfere with the window management API... So I need to investigate a bit. Do you have error messages when arbtt is launched manually, and then the Mac goes to sleep and wakeup?

One solution would be to prevent sleep (there are functions to do that in IOKit), but it would be a brutal solution...

**Comment by waldyrious** [comment]
No, I never saw any error messages... but I could change the command to start arbtt-capture to send stderr to a log file to see if I can grab any useful data.

**Comment by vrasneur** [comment]
Yes, redirecting to stderr would be useful :)

**Comment by waldyrious** [comment]
Just did that and rebooted. I'm getting a bunch of "Cannot get the windows information array." errors there :/

**Comment by vrasneur** [comment]
If you have this error, it means the CGWindowListCopyWindowInfo() call failed.
I will try to reproduce...

**Comment by vrasneur** [comment]
From /System/Library/Frameworks/CoreGraphics.framework/Headers/CGWindow.h (for CGWindowListCopyWindowInfo()) :

`This function returns NULL if the caller is not running within a Quartz
   GUI session or the window server is disabled. You should release the
   array when you are finished using it.`

So, maybe when you launch arbtt-capture with crontab, maybe there is no graphical session available.

I think crontab is deprecated in Mac OS X, can you try with launchd ?

**Comment by waldyrious** [comment]
Sure. It may have been the case that when I first tried out `arbtt-capture` it worked because I started it manually, but ever since I set up the crontab it hasn't been working. I'll test later to confirm :)

**Comment by waldyrious** [comment]
@vrasneur I tried using `launchd`, but I must be doing something wrong, because the script doesn't seem to be running. Do you see something wrong here?

```
$ cat ~/Library/LaunchAgents/local.waldyrious.arbtt.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>local.waldyrious.arbtt</string>
        <key>ProgramArguments</key>
        <array>
            <string>/Users/waldyrious/.cabal/bin/arbtt-capture</string>
        </array>
    </dict>
</plist>

$ launchctl list | grep arbtt
-	0	local.waldyrious.arbtt
```

**Comment by vrasneur** [comment]
I can launch arbtt-capture automatically using this plist file (attached) in ~/Library/LaunchAgents.

And then, to load it (one time):
`launchctl load /Users/Vincent/Library/LaunchAgents/com.foo.arbtt.plist`

I use "RunAtLoad" (with a true value), so that the program starts when I log in.
And "KeepAlive" (with a true value), so that arbtt-capture is restarted if it crashes.

When I do a "grep", eveything seems normal:
`$ launchctl list| grep arbtt`
`657 0	com.foo.arbtt`

[com.foo.arbtt.plist.txt](https://github.com/nomeata/darcs-mirror-arbtt/files/405767/com.foo.arbtt.plist.txt)

**Comment by waldyrious** [comment]
Oh, that makes sense! From man launchd.plist:

> **RunAtLoad** \<boolean>
>     This optional key is used to control whether your job is launched once at the time the job is loaded. **The default is
>     false.** (...)

The various pages I read while learning about launchd seemed to imply that any .plist placed in ~/LaunchAgents will be run at system start. The fact that they're called "launch agents" and "launch daemons" certainly contributed to the confusion. But it makes sense: they are *loaded* at launch, but *run* at the schedule specified in the plist file. I'll give it a try with RunAtLoad and report back.

**Comment by waldyrious** [comment]
Hurray! It works :) I've created a PR to add these instructions to the README.

**Comment by vrasneur** [comment]
Great! :)

Launchd's plist files are badly documented, so it's a good idea to add instructions to the README. The PR will be very useful ;)
